# pest_profilecoq.py


pest_profiles = {
    "FallArmyworm": {
        "common_name": "FallArmyworm",
        "scientific_name": "Spodoptera frugiperda",
        "type": "Insect",
        "category": "FieldPest",
        "damage_effects": ["ReducedPhotosynthesis", "YieldLoss"],
        "plant_parts_attacked": ["Leaf", "Whorl", "Cob"],
        "crop_stages_affected": ["Vegetative", "Reproductive"],
        "control_actions": ["ChemicalInsecticides", "NaturalEnemies", "PushPullSystem"],
        "control_methods_general": ["Chemical", "Biological", "Cultural"],
        "description" : "Larvae feed on leaves, whorl, and ears; highly mobile and destructive.",
        "damage_summary":"Causes severe defoliation and reduced yields in maize fields worldwide."
    },
    "AfricanArmyworm": {
        "common_name": "AfricanArmyworm",
        "scientific_name": "Spodoptera exempta",
        "type": "Insect",
        "category": "FieldPest",
        "damage_effects": ["ReducedPhotosynthesis", "YieldLoss"],
        "plant_parts_attacked": ["Leaf"],
        "crop_stages_affected": ["Vegetative", "Reproductive"],
        "control_actions": ["ChemicalInsecticides", "NaturalEnemies"],
        "control_methods_general": ["Chemical", "Biological"],
        "description" : "Larvae feed on maize leaves, sometimes leading to complete defoliation.",
        "damage_summary":"Causes defoliation and yield loss."
    },
    "MaizeStalkBorer": {
        "common_name": "MaizeStalkBorer",
        "scientific_name": "Busseola fusca",
        "type": "Insect",
        "category": "FieldPest",
        "damage_effects": ["YieldLoss", "LodgingEffect"],
        "plant_parts_attacked": ["Stem"],
        "crop_stages_affected": ["Vegetative", "Reproductive"],
        "control_actions": ["CropRotation"],
        "control_methods_general": ["Cultural"],
        "description" : "Larvae bore into maize stems, causing deadheart and lodging.",
        "damage_summary":"Stem tunneling, deadheart, lodging, reduced nutrient uptake, yield loss."
    },
    "SpottedStemBorer": {
        "common_name": "SpottedStemBorer",
        "scientific_name": "Chilo partellus",
        "type": "Insect",
        "category": "FieldPest",
        "damage_effects": ["YieldLoss", "LodgingEffect"],
        "plant_parts_attacked": ["Stem"],
        "crop_stages_affected": ["Vegetative", "Reproductive"],
        "control_actions": ["CropRotation"],
        "control_methods_general": ["Cultural"],
        "description" : "Stem borer larvae bore maize stems, affecting plant growth.",
        "damage_summary" : "Stem damage and lodging, reduced yield."
    },
    "PinkStemBorer": {
        "common_name": "PinkStemBorer",
        "scientific_name": "Sesamia calamistis",
        "type": "Insect",
        "category": "FieldPest",
        "damage_effects": ["YieldLoss", "LodgingEffect"],
        "plant_parts_attacked": ["Stem"],
        "crop_stages_affected": ["Vegetative", "Reproductive"],
        "control_actions": ["CropRotation"],
        "control_methods_general": ["Cultural"],
         "description" : "Bores into maize stems causing stem tunneling and plant weakening.",
        "damage_summary" : "Stem tunneling, deadheart, lodging, yield loss."
    },
    "CornEarworm": {
        "common_name": "CornEarworm",
        "scientific_name": "Helicoverpa zea",
        "type": "Insect",
        "category": "FieldPest",
        "damage_effects": ["YieldLoss"],
        "plant_parts_attacked": ["Cob"],
        "crop_stages_affected": ["Reproductive"],
        "control_actions": ["ChemicalInsecticides", "NaturalEnemies"],
        "control_methods_general": ["Chemical", "Biological"],
         "description" : "Larvae feed on maize cobs, reducing kernel quality.",
        "damage_summary" : "Cob damage, grain loss, reduced yield"
    },
    "Cutworm": {
        "common_name": "Cutworm",
        "scientific_name": "Agrotis spp.",
        "type": "Insect",
        "category": "FieldPest",
        "damage_effects": ["YieldLoss"],
        "plant_parts_attacked": ["Stem"],
        "crop_stages_affected": ["Seedling"],
        "control_actions": ["ChemicalInsecticides", "FieldSanitation"],
        "control_methods_general": ["Chemical", "Cultural"],
         "description" : "Larvae cut seedlings at soil level, causing deadheart in young plants.",
        "damage_summary" : "Deadheart, reduced establishment, yield loss."
    },
    "Wireworm": {
        "common_name": "Wireworm",
        "scientific_name": "Elateridae spp.",
        "type": "Insect",
        "category": "FieldPest",
        "damage_effects": ["ReducedNutrientUptake", "PlantDeath"],
        "plant_parts_attacked": ["Root"],
        "crop_stages_affected": ["Seed"],
        "control_actions": ["ChemicalInsecticides"],
        "control_methods_general": ["Chemical"],
         "description" : "Larvae feed on maize roots, stunting plant growth.",
        "damage_summary" : "Root damage, reduced nutrient uptake, plant death, yield loss."
    },
    "WhiteGrub": {
        "common_name": "WhiteGrub",
        "scientific_name": "Phyllophaga spp.",
        "type": "Insect",
        "category": "FieldPest",
        "damage_effects": ["ReducedNutrientUptake", "PlantDeath"],
        "plant_parts_attacked": ["Root"],
        "crop_stages_affected": ["Seedling", "Vegetative"],
        "control_actions": ["ChemicalInsecticides"],
        "control_methods_general": ["Chemical"],
         "description" : "Larvae feed on maize roots, leading to poor growth.",
        "damage_summary" : "Root damage, stunted plants, yield loss."
    },
    "Termite": {
        "common_name": "Termite",
        "scientific_name": "Macrotermes spp.",
        "type": "Insect",
        "category": "FieldPest",
        "damage_effects": ["ReducedNutrientUptake", "PlantDeath"],
        "plant_parts_attacked": ["Root"],
        "crop_stages_affected": ["Vegetative", "Reproductive"],
        "control_actions": ["FieldSanitation", "ChemicalInsecticides"],
        "control_methods_general": ["Cultural", "Chemical"],
         "description" : "Feed on maize roots and stems, weakening plants.",
        "damage_summary" : "Root and stem damage, plant death, yield loss."
    },
    "ShootFly": {
        "common_name": "ShootFly",
        "scientific_name": "Atherigona soccata",
        "type": "Insect",
        "category": "FieldPest",
        "damage_effects": ["PlantDeath"],
        "plant_parts_attacked": ["Whorl"],
        "crop_stages_affected": ["Vegetative"],
        "control_actions": ["ResistantVarieties", "FieldSanitation"],
        "control_methods_general": ["Integrated", "Cultural"],
         "description" : "Larvae feed in the central whorl causing deadheart.",
        "damage_summary" : "Deadheart formation, reduced yield."
    },
    "Aphid": {
        "common_name": "Aphid",
        "scientific_name": "Rhopalosiphum maidis",
        "type": "Insect",
        "category": "FieldPest",
        "damage_effects": ["YieldLoss"],
        "plant_parts_attacked": ["Leaf"],
        "crop_stages_affected": ["Vegetative", "Reproductive"],
        "control_actions": ["NaturalEnemies", "Biopesticides"],
        "control_methods_general": ["Biological"],
         "description" : "Suck sap from maize leaves and transmit viruses.",
        "damage_summary" : "Sap loss, virus transmission, yield reduction."
    },
    "Leafhopper": {
        "common_name": "Leafhopper",
        "scientific_name": "Cicadulina spp.",
        "type": "Insect",
        "category": "FieldPest",
        "damage_effects": ["YieldLoss"],
        "plant_parts_attacked": ["Leaf"],
        "crop_stages_affected": ["Vegetative", "Reproductive"],
        "control_actions": ["NaturalEnemies"],
        "control_methods_general": ["Biological"],
         "description" : "Sucks sap and transmits maize streak virus.",
        "damage_summary" : "Virus transmission, stunted growth, yield loss."
    },
    "Thrips": {
        "common_name": "Thrips",
        "scientific_name": "Thrips tabaci",
        "type": "Insect",
        "category": "FieldPest",
        "damage_effects": ["YieldLoss"],
        "plant_parts_attacked": ["Leaf"],
        "crop_stages_affected": ["Vegetative", "Reproductive"],
        "control_actions": ["ChemicalInsecticides", "Biopesticides"],
        "control_methods_general": ["Chemical", "Biological"],
         "description" : "Feed on leaf tissues causing silvering and sap loss.",
        "damage_summary" : "Sap loss, reduced photosynthesis, yield loss."
    },
    "Whitefly": {
        "common_name": "Whitefly",
        "scientific_name": "Bemisia tabaci",
        "type": "Insect",
        "category": "FieldPest",
        "damage_effects": ["YieldLoss"],
        "plant_parts_attacked": ["Leaf"],
        "crop_stages_affected": ["Vegetative", "Reproductive"],
        "control_actions": ["NaturalEnemies", "Biopesticides"],
        "control_methods_general": ["Biological"],
         "description" : "Feeds on maize leaves and transmits viruses.",
        "damage_summary" : "Sap loss, virus transmission, reduced yield."
    },
    "Grasshopper": {
        "common_name": "Grasshopper",
        "scientific_name": "Acrididae spp.",
        "type": "Insect",
        "category": "FieldPest",
        "damage_effects": ["ReducedPhotosynthesis", "YieldLoss"],
        "plant_parts_attacked": ["Leaf"],
        "crop_stages_affected": ["Vegetative"],
        "control_actions": ["HandPicking", "ChemicalInsecticides"],
        "control_methods_general": ["Mechanical", "Chemical"],
         "description" : "Feeds on maize leaves, sometimes causing defoliation.",
        "damage_summary" : "Defoliation and reduced photosynthesis."
    },
    "Locust": {
        "common_name": "Locust",
        "scientific_name": "Locusta migratoria",
        "type": "Insect",
        "category": "FieldPest",
        "damage_effects": ["ReducedPhotosynthesis", "YieldLoss"],
        "plant_parts_attacked": ["Leaf"],
        "crop_stages_affected": ["Vegetative"],
        "control_actions": ["ChemicalInsecticides", "NaturalEnemies"],
        "control_methods_general": ["Chemical", "Biological"],
         "description" : "Feeds on maize leaves in swarms.",
        "damage_summary" : "Severe defoliation, reduced yield."
    },
    "Rootworm": {
        "common_name": "Rootworm",
        "scientific_name": "Diabrotica spp.",
        "type": "Insect",
        "category": "FieldPest",
        "damage_effects": ["ReducedNutrientUptake", "PlantDeath"],
        "plant_parts_attacked": ["Root"],
        "crop_stages_affected": ["Vegetative"],
        "control_actions": ["ChemicalInsecticides", "CropRotation"],
        "control_methods_general": ["Chemical", "Cultural"],
         "description" : "Larvae feed on roots, weakening plants.",
        "damage_summary" : "Root damage, plant death, yield reduction."
    },
    "NematodePest": {
        "common_name": "NematodePest",
        "scientific_name": "Meloidogyne spp.",
        "type": "Nematode",
        "category": "FieldPest",
        "damage_effects": ["ReducedNutrientUptake", "PlantDeath"],
        "plant_parts_attacked": ["Root"],
        "crop_stages_affected": ["Seedling", "Vegetative"],
        "control_actions": ["CropRotation", "Biopesticides"],
        "control_methods_general": ["Cultural", "Biological"],
         "description" : "Root-knot nematodes damage maize roots.",
        "damage_summary" : "Root damage, stunted growth, yield loss."
    },
    "MaizeWeevil": {
        "common_name": "MaizeWeevil",
        "scientific_name": "Sitophilus zeamais",
        "type": "Insect",
        "category": "StoragePest",
        "damage_effects": ["YieldLoss"],
        "plant_parts_attacked": ["Grain"],
        "crop_stages_affected": ["Storage"],
        "control_actions": ["FieldSanitation", "ChemicalInsecticides"],
        "control_methods_general": ["Cultural", "Chemical"],
         "description" : "Infests stored maize grains causing weight loss.",
        "damage_summary" : "Grain loss, reduced quality, post-harvest losses."
    },
    "LargerGrainBorer": {
        "common_name": "LargerGrainBorer",
        "scientific_name": "Prostephanus truncatus",
        "type": "Insect",
        "category": "StoragePest",
        "damage_effects": ["YieldLoss"],
        "plant_parts_attacked": ["Grain"],
        "crop_stages_affected": ["Storage"],
        "control_actions": ["FieldSanitation", "ChemicalInsecticides"],
        "control_methods_general": ["Cultural", "Chemical"],
         "description" : "Infests stored maize grains, tunneling kernels.",
        "damage_summary" : "Grain loss, reduced quality, post-harvest losses."
    },
    "AngoumoisGrainMoth": {
        "common_name": "AngoumoisGrainMoth",
        "scientific_name": "Sitotroga cerealella",
        "type": "Insect",
        "category": "StoragePest",
        "damage_effects": ["QualityDeterioration"],
        "plant_parts_attacked": ["Grain"],
        "crop_stages_affected": ["Storage"],
        "control_actions": ["ChemicalInsecticides", "NaturalEnemies"],
        "control_methods_general": ["Chemical", "Biological"],
         "description" : "Infests stored maize grains; larvae feed inside kernels.",
        "damage_summary" : "Grain loss, quality deterioration"
    },
    "FlourBeetle": {
        "common_name": "FlourBeetle",
        "scientific_name": "Tribolium spp.",
        "type": "Insect",
        "category": "StoragePest",
        "damage_effects": ["QualityDeterioration"],
        "plant_parts_attacked": ["Grain"],
        "crop_stages_affected": ["Storage"],
        "control_actions": ["ChemicalInsecticides"],
        "control_methods_general": ["Chemical"],
         "description" : "Attacks stored maize grains and flour products.",
        "damage_summary" : "Grain loss, quality deterioration."
    },
    "Rodent": {
        "common_name": "Rodent",
        "scientific_name": "Rattus rattus",
        "type": "Vertebrate",
        "category": "VertebratePest",
        "damage_effects": ["YieldLoss"],
        "plant_parts_attacked": ["Grain"],
        "crop_stages_affected": ["Storage"],
        "control_actions": ["HandPicking", "TrapSetting"],
        "control_methods_general": ["Mechanical"],
         "description" : "Feeds on stored and field maize grains.",
        "damage_summary" : "Grain loss, reduced yield"
    },
    "Bird": {
        "common_name": "Bird",
        "scientific_name": "Quelea quelea",
        "type": "Vertebrate",
        "category": "VertebratePest",
        "damage_effects": ["YieldLoss"],
        "plant_parts_attacked": ["Cob", "Grain"],
        "crop_stages_affected": ["Reproductive", "Storage"],
        "control_actions": ["Scarecrows", "Netting"],
        "control_methods_general": ["Mechanical"],
         "description" : "Feeds on maize grains in the field and storage.",
        "damage_summary" : "Grain loss, yield reduction."
    }
}
